name: Create release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build.tar.gz
