name: Create release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          version: lts/*
      - run: npm install --global web-ext
      - uses: actions/checkout@v4
      - run: make build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            web-ext-artifacts/build.tar.gz
            web-ext-artifacts/build.zip
      - name: Publish
        env:
          ADDONS_MOZ_JWT_ISSUER: ${{ secrets.ADDONS_MOZ_JWT_ISSUER }}
          ADDONS_MOZ_JWT_SECRET: ${{ secrets.ADDONS_MOZ_JWT_SECRET }}
        run: make publish
